src/libnmea_navsat_driver/parser.py

Remaining problem with NovAtel receivers was with an empty field specified for num_satellites.

Fix parse error, issue #5.

---

src/libnmea_navsat_driver/parser.py

GLONASS capable devices send different NMEA sentences, which are
basically identical to the GPS sentences, but with other prefixes.

Add GLONASS support

---

src/libnmea_navsat_driver/driver.py

Updated driver to accept status of 9 which some novatel recievers report for a WAAS (SBAS) fix.
See http://www.novatel.com/support/known-solutions/which-novatel-position-types-correspond-to-the-gga-quality-indicator/

Novatel OEM4 Support Fix

---

CMakeLists.txt
package.xml

By going to package format 2, we can make roslint a test depend rather than build depend.

Cleanup of CMakeLists, package.xml.

---

src/libnmea_navsat_driver/driver.py

Removed the automatic prefixing of forward slash, but to be consistent with the current default behavior,
the default frame_id has been set to `/gps` with the prepended forward slash.

Removed automatic prefixing of forward slash to frame_id.

---

CMakeLists.txt
scripts/nmea_socket_driver
src/libnmea_navsat_driver/driver.py
src/libnmea_navsat_driver/parser.py

This PR addresses/fixes comments on https://github.com/ros-drivers/nmea_navsat_driver/pull/16

Socket driver

---

src/libnmea_navsat_driver/driver.py
src/libnmea_navsat_driver/parser.py

* Adds support for IMU aided GPS systems like the Applanix POS/MV, whose NMEA strings typically begin '$IN'. (e.g. $INGGA).
* Adds support for VTG messages, which contain Course Over Ground and Speed Made Good. These are useful when not using RMC messages and you don't have a heading sensor.
This is a duplicate of #30, which was merged to jade-devel, to port that change forward to master.

Add support for IMU aided GPS systems (#30)

---

src/libnmea_navsat_driver/driver.py

Remove the automatic prefixing of forward slash, but to be consistent with the current default behavior, the default frame_id has been set to /gps with the prepended forward slash.
This is a duplicate of #33, which was merged to jade-devel, to port that change forward to master.

Remove automatic prefixing of forward slash to frame_id. (#33)

---

package.xml

Re-added here: https://github.com/ros-drivers/nmea_navsat_driver/pull/25.

Removed roslint as build depend.

---

package.xml

Fix for #65. To test:
```bash
docker run -it osrf/ros:crystal-desktop 
apt update && apt install -y python3-colcon-common-extensions
(cd /usr/bin && ln -s pip3 pip)
rosdep init
rosdep update
mkdir -p workspace/src
cd workspace/src
git clone https://github.com/evenator/nmea_navsat_driver.git -b ros2-fix-dependencies
git clone https://github.com/ros-drivers/nmea_msgs.git -b ros2
cd ..
rosdep install -i --from-paths src --rosdistro crystal
```

Fix Dependencies in Ros2

---

scripts/nmea_serial_driver.py
scripts/nmea_socket_driver.py
scripts/nmea_topic_driver.py
setup.cfg
src/libnmea_navsat_driver/driver.py
src/libnmea_navsat_driver/parser.py

- Fix PEP8 violations with a combination of `autopep8` and manual tweaks.
- Update the `setup.cfg` file with configuration for `pycodestyle`.
`pycodestyle scripts/* src setup.py` now passes.

Fix PEP8 Violations in ROS 2

---

scripts/nmea_serial_driver
scripts/nmea_socket_driver
scripts/nmea_topic_driver
scripts/nmea_topic_serial_reader
setup.cfg
src/libnmea_navsat_driver/checksum_utils.py
src/libnmea_navsat_driver/driver.py
src/libnmea_navsat_driver/parser.py

- Fix PEP8 violations with a combination of `autopep8` and manual tweaks.
- Add a `setup.cfg` file with configuration for `pycodestyle`
`pycodestyle scripts/* src setup.py` now passes.

Fix PEP8 Violations

---

scripts/nmea_topic_serial_reader.py
setup.py

- Fix #72 (`no module named scripts.nmea_topic_serial_driver`)
- Fix exception handling in nmea_topic_serial_reader  (`'rclpy' has no attribute 'ROSInterruptException'`)
I've updated the exception handling to match the serial driver node. It's catch-all handling, which isn't ideal, but it's an improvement over trying to catch an exception that doesn't exist.

Fix nmea_topic_serial_reader name

---

scripts/nmea_serial_driver
scripts/nmea_topic_driver
scripts/nmea_topic_serial_reader
setup.py
src/libnmea_navsat_driver/nodes/nmea_serial_driver.py
src/libnmea_navsat_driver/nodes/nmea_socket_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_serial_reader.py

Move all of the actual code for each node into its own module in a new "nodes" package within libnmea_navsat_driver. Make each script only 2 lines: import and call main().
This will reduce the difference between ROS 1 and ROS 2 code, because ROS 2 uses Python entry points to install executables.
Addresses #75

Refactor all nodes into entrypoint scripts

---

setup.py
src/libnmea_navsat_driver/nodes/nmea_serial_driver.py
src/libnmea_navsat_driver/nodes/nmea_socket_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_serial_reader.py

Since these modules will no longer be called as scripts in ROS 2, move them to a nodes subpackage, and remove the option to call them as executables.
Addresses #75 for ROS 2.

ROS 2: Remove scripts directory in favor of a nodes subpackage

---

src/libnmea_navsat_driver/nodes/nmea_socket_driver.py

This is deviating a little from #90. I recommend testing on Windows since `select()` behaves slightly differently there, and on Python 2.7 if that is still supported.
Rather than using low level socket APIs, this uses the Python [SocketServer](https://docs.python.org/3.7/library/socketserver.html) module. This simplifies the code by several lines and makes it easier to support TCP packets in the future.
The `buffer_size` parameter is no longer necessary because this is an internal detail of `UDPServer`.

Rewrite nmea_socket_driver to use serversocket

---

CMakeLists.txt
launch/nmea_serial_driver.launch
launch/nmea_socket_driver.launch
package.xml
scripts/nmea_serial_driver
scripts/nmea_socket_driver
scripts/nmea_topic_driver
scripts/nmea_topic_serial_reader
setup.cfg
setup.py
src/libnmea_navsat_driver/__init__.py
src/libnmea_navsat_driver/checksum_utils.py
src/libnmea_navsat_driver/driver.py
src/libnmea_navsat_driver/nodes/__init__.py
src/libnmea_navsat_driver/nodes/nmea_serial_driver.py
src/libnmea_navsat_driver/nodes/nmea_socket_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_serial_reader.py
src/libnmea_navsat_driver/parser.py

This PR backports the following PRs from `master` to `melodic-devel`:
- #59 Remove `roslint` as a build dependency
- #60 Add `nmea_serial_driver` launch file
- #68 Fix PEP8 violations
- #76 Refactor nodes into entrypoint scripts
- #79 Add an option to use GNSS time and improve time parsing
- #88 Add documentation and clean up
- #92 rewrite `nmea_socket_driver` to user `serversocket`
These changes do not break the existing API, so they can be backported to the already-released Melodic branch.

Backport Recent Changes to Melodic

---

setup.py

Some warnings are now showing when installing packages that are missing the `resource` folder and those that does not explicitly install `package.xml` in the share folder.
This PR fixes those issues to remove warnings and future-proof the package.

ROS2: Eloquent changes for python packages

---

src/libnmea_navsat_driver/parser.py

NMEA uses a * character to delimit the beginning of the regex, so use a regex that matches * and , as the field delimiter.
Fixes #86

Use a regex to split tokens in parser

---

src/libnmea_navsat_driver/parser.py

nmea_topic_driver gets raw NMEA sentences. Those can contain carriage returns and new line. nmea_topic_driver won't parse messages with this characters. They will be removed before parsing now.

nmea_topic_driver Ignore carriage returns and new lines.

---

package.xml

When building the package and running the driver with minimal dependencies installed, a Python error appears because the dependency on tf is not declared in package.xml. Declare that dependency.
Fixes #62.

Add missing dependency on tf

---

package.xml

This allows rosdep to find the correct serial package and install it.

Update pyserial dependency to install it with rosdep

---

launch/nmea_serial_driver.launch.py

`get_default_launch_description` is non existing anymore in foxy as discussed in https://github.com/ros2/launch_ros/pull/128 so I removed it.
I also changed `node_executable` to `executable` to adhere to the latest foxy API.

Make launch file foxy compatible.

---

src/libnmea_navsat_driver/driver.py

valid_fix should be determined by checking if the fix_type is greater than 0, not the gps_qual. This was never correct, but it at least ran in Python 2. In Python 3, it causes a TypeError.

Fix valid_fix check (#111)

---

CMakeLists.txt
package.xml
scripts/nmea_serial_driver
scripts/nmea_socket_driver
scripts/nmea_topic_driver
scripts/nmea_topic_serial_reader
src/libnmea_navsat_driver/nodes/nmea_serial_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_serial_reader.py

Updates for ROS Noetic:
- CMake minimum version is now 3.0.2
- Python version is now 3
- Package.xml version is now 3
Tested on ROS Noetic in Ubuntu 20.04 (Focal) under Windows Subsystem for Linux. Serial drivers working as expected.

Update to Python3 for ROS Noetic

---

doc/conf.py

Fix some Python formatting, which should make the ROS build farm PR tests pass.

Fix lint in doc config python

---

src/libnmea_navsat_driver/parser.py

If a UTC time string is of the format `HHMMSS `instead of `HHMMSS.SS`, as observed on some Garmin receivers, GPGGA message parsing would fail with a `ValueError`.
Only attempt to parse nanoseconds if the UTC time string is long enough.

Fix UTC time parsing #105

---

src/libnmea_navsat_driver/driver.py
src/libnmea_navsat_driver/nodes/nmea_serial_driver.py
src/libnmea_navsat_driver/nodes/nmea_topic_serial_reader.py

Handle decoding errors when reading from a serial port. NMEA sentences should be ASCII-encoded, but if malformed data comes in from the serial port, it won't decode properly.
If the exception isn't handled, the node will crash. This commonly happens on startup.
When tested with a BU-353S4 receiver, I reproduced the error reported in #115 and now it prints the following warning and does not crash:
```
[WARN] [1602352879.808924]: Skipped reading a line from the serial device because it could not be decoded as an ASCII string. The bytes were b'f\x06\x16&\x06\xe6\x06\x06\x06\xc6F\x06&v\xe6&\x86Fv\xc6\xe6c\x06v\x96V\x86\xe6\x96\x06f\x16\xc6v\x8dY\xc6\x06v\xc6\x16\xe6\x16\xc6&Vv\xe6v\xc6\xd6c\xd666\xe6\x06\xc6\xd6c\xc6\x06\x06\x06\x06\xa6f6k'
```
Also a couple of codestyle fixes.

Fix #115: Decoding errors

---

src/libnmea_navsat_driver/nodes/nmea_socket_driver.py

RosNMEADriver.add_sentence() expects the first argument to be a str, not a bytes object.
This was properly decoded in the other node types, but not in the UDP socket server.
Should fix #120

Decode lines from the UDP server before passing them to the driver

---

.github/workflows/ci.yaml
test/test_driver.py

Idling for 9 minutes and then counting these 9 minutes against the 10 minutes threshold was by far a new record from what I've seen so far: https://github.com/ros-drivers/nmea_navsat_driver/runs/5672759022?check_suite_focus=true
Therefore extending the limit.
In addition the ROS buildfarm debian builder seems to have an inconsistent behavior concerning the time it takes to open virtual serial ports, causing the build to crash sometimes. This is also fixed here.
Signed-off-by: Gabriel Gaessler <gabriel.gaessler@de.bosch.com>

Extend workflow time and fix debian serial port bug

---

src/libnmea_navsat_driver/checksum_utils.py

Removing this print statement to avoid spamming the console with NMEA strings.

Removed printing every time the checksum is checked.

---

src/libnmea_navsat_driver/parser.py

Some receivers first report only time without date during startup making the driver crash when started before the receiver has an initial fully qualified time fix, so including the date. This PR fixes the bug.
As a side effect this also re-runs the Github actions, see https://github.com/ros-drivers/nmea_navsat_driver/pull/136#issuecomment-1074558620
Signed-off-by: Gabriel Gaessler <gabriel.gaessler@de.bosch.com>

Fix GNSS receiver startup bug
